# yoCore v1.0 by Yochran
# https://github.com/Yochran

# Rank names MUST be in all caps!
Ranks:
  OWNER:
    Prefix: "&7[&4Owner&7] &4"
    Color: "&4"
    Display: "&4Owner"
    Priority: 1
    GrantItem: "REDSTONE_BLOCK"
    GrantPermission: "yocore.grant.owner"
  DEVELOPER:
    Prefix: "&7[&5&oDeveloper&7] &5&o"
    Color: "&5&o"
    Display: "&5&oDeveloper"
    Priority: 2
    GrantItem: "PURPLE_WOOL"
    GrantPermission: "yocore.grant.developer"
  MANAGER:
    Prefix: "&7[&c&oManager&7] &c&o"
    Color: "&c&o"
    Display: "&c&oManager"
    Priority: 3
    GrantItem: "RED_WOOL"
    GrantPermission: "yocore.grant.manager"
  ADMIN:
    Prefix: "&7[&cAdmin&7] &c"
    Color: "&c"
    Display: "&cAdmin"
    Priority: 4
    GrantItem: "RED_WOOL"
    GrantPermission: "yocore.grant.admin"
  SENIOR-MOD:
    Prefix: "&7[&6&oSenior-Mod&7] &6&o"
    Color: "&6&o"
    Display: "&6&oMod"
    Priority: 5
    GrantItem: "ORANGE_WOOL"
    GrantPermission: "yocore.grant.seniormod"
  MOD:
    Prefix: "&7[&6Mod&7] &6"
    Color: "&6"
    Display: "&6Mod"
    Priority: 6
    GrantItem: "ORANGE_WOOL"
    GrantPermission: "yocore.grant.mod"
  TRIAL-MOD:
    Prefix: "&7[&eTrial-Mod&7] &e"
    Color: "&e"
    Display: "&eTrial-Mod"
    Priority: 7
    GrantItem: "YELLOW_WOOL"
    GrantPermission: "yocore.grant.trialmod"
  BUILDER:
    Prefix: "&7[&2Builder&7] &2"
    Color: "&2"
    Display: "&2Builder"
    Priority: 8
    GrantItem: "GREEN_WOOL"
    GrantPermission: "yocore.grant.builder"
  DEFAULT:
    Prefix: "&7"
    Color: "&7"
    Display: "&7Default"
    Priority: 9
    GrantItem: "GRAY_WOOL"
    GrantPermission: "yocore.grant.default"

ChatFormat: "%player_prefix%&7: &f%message%"

JoinMessage:
  Enabled: true
  Message: "&7(&a+&7) %player%"
  Staff:
    Enabled: true
    Message: "&b[SC] %player% &bjoined &3the server."

QuitMessage:
  Enabled: true
  Message: "&7(&c-&7) %player%"
  Staff:
    Enabled: false
    Message: "&b[SC] %player% &bleft &3the server."

SetRank:
  IncorrectUsage: "&cIncorrect Usage! /setrank <player> <rank>"
  InvalidPlayer: "&cInvalid Player!"
  InvalidRank: "&cInvalid Rank!"
  ConsoleOnly: "&cThis command is Console only!"
  ExecutorMessage: "&bYou have set %target%&b's rank to %rank%&b."
  TargetMessage: "&bYour rank has been set to %rank%&b."

SilentPrefix: "&7(Silent) "

Warn:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /warn <player> [-s] <reason>"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have warned %target% &bfor &3%reason%&b."
  TargetMessage: "&6&l<!> &cYou have been warned for &4%reason%&c. &6&l<!>"
  BroadcastMessage: "%executor% &bhas warned %target%&b."

Kick:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /kick <player> [-s] <reason>"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have kicked %target% &bfor &3%reason%&b."
  BroadcastMessage: "%executor% &bhas kicked %target%&b."
  TargetScreen: |-
    &cYou've been &4kicked &cfrom this server.
    &cYou were kicked for&7: &f%reason%&7.

Mute:
  NoPermission: "&cYou do not have permission to use that command."
  InvalidPlayer: "&cInvalid Player!"
  TargetIsMuted: "&cTarget is already muted!"
  Permanent:
    IncorrectUsage: "&cIncorrect Usage! /mute <player> [-s] <reason>"
    ExecutorMessage: "&bYou have permanently muted %target% &bfor &3%reason%&b."
    TargetMessage: "&6&l<!> &cYou have been &4permanently &cmuted for &4%reason%&c. &6&l<!>"
    BroadcastMessage: "%executor% &bhas permanently muted %target%&b."
    TargetAttemptToSpeak: |-
      &cYou cannot speak as you are muted for &4%reason%&c.
      &cThis mute will &4not &cexpire.
  Temporary:
    IncorrectUsage: "&cIncorrect Usage! /tempmute <player> <duration> [-s] <reason>"
    ExecutorMessage: "&bYou have temporarily muted %target% &bfor &3%reason%&b. &7(%duration%)"
    TargetMessage: "&6&l<!> &cYou have been temporarily muted for &4%reason%&c. &7(%duration%) &6&l<!>"
    BroadcastMessage: "%executor% &bhas temporarily muted %target%&b."
    TargetAttemptToSpeak: |-
      &cYou cannot speak as you are muted for &4%reason%&c.
      &cThis mute will expire on &4%expiration%&c.

Unmute:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /unmute <player> [-s]"
  InvalidPlayer: "&cInvalid Player!"
  TargetIsNotMuted: "&cTarget is not muted!"
  ExecutorMessage: "&bYou have unmuted %target%&b."
  TargetMessage: "&6&l<!> &aYou have been unmuted. &6&l<!>"
  BroadcastMessage: "%executor% &bhas unmuted %target%&b."

Ban:
  NoPermission: "&cYou do not have permission to use that command."
  InvalidPlayer: "&cInvalid Player!"
  TargetIsBanned: "&cTarget is already banned!"
  Permanent:
    IncorrectUsage: "&cIncorrect Usage! /ban <player> [-s] <reason>"
    ExecutorMessage: "&bYou have permanently banned %target% &bfor &3%reason%&b."
    BroadcastMessage: "%executor% &bhas permanently banned %target%&b."
    TargetMessage: |-
      &cYou've been &4banned &cfrom this server.
      &cYou were banned for&7: &f%reason%&7.
      &cThis ban will &4not &cexpire.
    TargetJoinScreen: |-
      &cYou cannot join this server as you are &4banned&c.
      &cYou were banned for&7: &f%reason%&7.
      &cThis ban will &4not &cexpire.
  Temporary:
    IncorrectUsage: "&cIncorrect Usage! /tempban <player> <duration> [-s] <reason>"
    ExecutorMessage: "&bYou have temporarily banned %target% &bfor &3%reason%&b. &7(%duration%)"
    BroadcastMessage: "%executor% &bhas temporarily banned %target%&b."
    TargetMessage: |-
      &cYou've been &4banned &cfrom this server.
      &cYou were banned for&7: &f%reason%&7.
      &cThis bann will expire on&7: &f%expiration%&7.
    TargetJoinScreen: |-
      &cYou cannot join this server as you are &4banned&c.
      &cYou were banned for&7: &f%reason%&7.
      &cThis bann will expire on&7: &f%expiration%&7.

Unban:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /unban <player> [-s]"
  InvalidPlayer: "&cInvalid Player!"
  TargetIsNotBanned: "&cTarget is not banned!"
  ExecutorMessage: "&bYou have unbanned %target%&b."
  BroadcastMessage: "%executor% &bhas unbanned %target%&b."

Blacklist:
  NoPermission: "&cYou do not have permission to use that command."
  InvalidPlayer: "&cInvalid Player!"
  TargetIsBlacklisted: "&cTarget is already blacklisted!"
  IncorrectUsage: "&cIncorrect Usage! /blacklist <player> [-s] <reason>"
  ExecutorMessage: "&bYou have permanently blacklisted %target% &bfor &3%reason%&b."
  BroadcastMessage: "%executor% &bhas permanently blacklisted %target%&b."
  TargetMessage: |-
    &cYou've been &4blacklisted &cfrom this server.
    &cYou were blacklisted for&7: &f%reason%&7.
    &cThis blacklist will &4not &cexpire.
  TargetJoinScreen: |-
    &cYou cannot join this server as you are &4blacklisted&c.
    &cYou were blacklisted for&7: &f%reason%&7.
    &cThis blacklist will &4not &cexpire.

Unblacklist:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /unblacklist <player> [-s]"
  InvalidPlayer: "&cInvalid Player!"
  TargetIsNotBlacklisted: "&cTarget is not blacklisted!"
  ExecutorMessage: "&bYou have unblacklisted %target%&b."
  BroadcastMessage: "%executor% &bhas unblacklisted %target%&b."

History:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /c <player>"
  InvalidPlayer: "&cInvalid Player!"

ClearHistory:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /clearhistory <player>"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have cleared %target%&b's punishment history."

Grant:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /grant <player>"
  InvalidPlayer: "&cInvalid Player!"
  Rank:
    Lore:
      - "&7&m----------------------------------------"
      - "&eSelecting this will grant %target% &ethe %rank% &erank."
      - "&r"
      - "%permission%"
      - "&7&m----------------------------------------"
  Duration:
    Items:
      TenSeconds:
        Item: "WHITE_WOOL"
        Name: "&f10 Seconds"
        ID: "10 Seconds"
        Slot: 10
      OneMinute:
        Item: "YELLOW_WOOL"
        Name: "&e1 Minute"
        ID: "1 Minute"
        Slot: 11
      FiveMinutes:
        Item: "ORANGE_WOOL"
        Name: "&65 Minutes"
        ID: "5 Minutes"
        Slot: 12
      ThirtyMinutes:
        Item: "RED_WOOL"
        Name: "&c30 Minutes"
        ID: "30 Minutes"
        Slot: 13
      OneHour:
        Item: "GREEN_WOOL"
        Name: "&21 Hour"
        ID: "1 Hour"
        Slot: 14
      ThreeHours:
        Item: "LIME_WOOL"
        Name: "&a3 Hours"
        ID: "3 Hours"
        Slot: 15
      OneDay:
        Item: "BLUE_WOOL"
        Name: "&91 Day"
        ID: "1 Day"
        Slot: 16
      OneWeek:
        Item: "CYAN_WOOL"
        Name: "&31 Week"
        ID: "1 Week"
        Slot: 20
      OneMonth:
        Item: "LIGHT_BLUE_WOOL"
        Name: "&b1 Month"
        ID: "1 Month"
        Slot: 21
      OneYear:
        Item: "PURPLE_WOOL"
        Name: "&51 Year"
        ID: "1 Year"
        Slot: 23
      Permanent:
        Item: "BEDROCK"
        Name: "&8Permanent"
        ID: "Permanent"
        Slot: 24
    Lore:
      - "&7&m----------------------------------------"
      - "&eSelecting this will set the duration to %duration%."
      - "&r"
      - "&7(%target%&7)"
      - "&7&m----------------------------------------"
  Reason:
    Items:
      NoReason:
        Item: "BEDROCK"
        Name: "&8No Reason"
        ID: "No Reason"
        Slot: 10
      Promoted:
        Item: "LIME_WOOL"
        Name: "&aPromoted"
        ID: "Promoted"
        Slot: 11
      Demoted:
        Item: "RED_WOOL"
        Name: "&cDemoted"
        ID: "Demoted"
        Slot: 12
      Famous:
        Item: "PINK_WOOL"
        Name: "&dFamous"
        ID: "Famous"
        Slot: 13
      Whitelisted:
        Item: "WHITE_WOOL"
        Name: "&fWhitelisted"
        ID: "Whitelisted"
        Slot: 14
      Testing:
        Item: "CYAN_WOOL"
        Name: "&3Testing"
        ID: "Testing"
        Slot: 15
      Other:
        Item: "GREEN_WOOL"
        Name: "&2Other"
        ID: "Other"
        Slot: 16
    Lore:
      - "&7&m----------------------------------------"
      - "&eSelecting this will set the reason to %reason%."
      - "&r"
      - "&7(%target%&7)"
      - "&7&m----------------------------------------"
  Confirm:
    Lore:
      - "&7&m----------------------------------"
      - "&6&lDetails:"
      - "&e "
      - "&eTarget: &6%target%"
      - "&eRank: &6%rank%"
      - "&eDuration: &6%duration%"
      - "&eReason: &6%reason%"
      - "&7&m----------------------------------"
    CancelledGrant: "&c&lGrant has been cancelled."
    ConfirmedGrant: |-
      &a&lGrant has been confirmed.
      &eGranted User: %target%
      &eGranted Rank: &6%rank%
      &eGrant Duration: &6%duration%
      &eGrant Reason: &6%reason%

GrantHistory:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /grants <player>"
  InvalidPlayer: "&cInvalid Player!"

ClearGrantHistory:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /cleargranthistory <player>"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have cleared %target%&b's grant history."

Ungrant:
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /ungrant <player> <id>"
  InvalidPlayer: "&cInvalid Player!"
  InvalidGrant: "&cInvalid Grant!"
  ExecutorMessage: "&bYou have revoked grant &3#%grant% &bfrom %target%&b."

StaffChat:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /sc <message>"
  Format: "&b[SC] %player%&7: &b%message%"

AdminChat:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /ac <message>"
  Format: "&c[AC] %player%&7: &b%message%"

ManagementChat:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /mc <message>"
  Format: "&4[MC] %player%&7: &b%message%"

StaffAlerts:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  ToggleOnMessage: "&bYou have turned &3on &bstaff alerts."
  ToggleOffMessage: "&bYou have turned &3off &bstaff alerts."
  # Different Alerts
  VanishOnSelf: "&7[%player% &eentered &7vanish.]"
  VanishOffSelf: "&7[%player% &eexited &7vanish.]"
  VanishOnOther: "&7[%player% &7put %target% &einto &7vanish.]"
  VanishOffOther: "&7[%player% &7took %target% &eout of &7vanish.]"
  HealSelf: "&7[%player% &ehealed &7themselves.]"
  HealOther: "&7[%player% &ehealed %target%&7.]"
  FeedSelf: "&7[%player% &efed &7themselves.]"
  FeedOther: "&7[%player% &efed %target%&7.]"

Vanish:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /vanish [player]"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessageOn: "&bYou have put %target% &binto &3vanish&b."
  ExecutorMessageOff: "&bYou have taken %target% &bout of &3vanish&b."
  TargetMessageOn: "&bYou are now in &3vanish&b."
  TargetMessageOff: "&bYou are no longer in &3vanish&b."

Gamemode:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /gamemode <gamemode> [player]"
  InvalidPlayer: "&cInvalid Player!"
  InvalidGamemode: "&cInvalid Gamemode!"
  ExecutorMessage: "&bYou have put %target% &binto &3%gamemode% &bmode."
  TargetMessage: "&bYou have entered &3%gamemode% &bmode."

Heal:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /heal [player]"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have healed %target%&b."
  TargetMessage: "&bYou have been healed."

Feed:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /feed [player]"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have fed %target%&b."
  TargetMessage: "&bYou have been fed."

Clear:
  MustBePlayer: "&cYou must be a player to use that command."
  NoPermission: "&cYou do not have permission to use that command."
  IncorrectUsage: "&cIncorrect Usage! /clear [player]"
  InvalidPlayer: "&cInvalid Player!"
  ExecutorMessage: "&bYou have cleared %target%&b's inventory."
  TargetMessage: "&bYour inventory has been cleared."

ClearChat:
  NoPermission: "&cYou do not have permission to use that command."
  MessageAfter: "&bChat has been &3cleared &bby %executor%&b."

MuteChat:
  NoPermission: "&cYou do not have permission to use that command."
  MessageOn: "&bChat has been &3muted &bby %executor%&b."
  MessageOff: "&bChat has been &3unmuted &bby %executor%&b."
  AttemptToSpeak: "&cYou cannot speak as chat is muted."