name: yoCore
version: ${project.version}
main: me.yochran.yocore.yoCore
api-version: 1.16
authors: [ Yochran ]
description: Remastered version of the vCores, combined into one plugin.
commands:
  Setrank:
    description: Set a players rank.
    aliases: [sr, srank]
  Warn:
    description: Warn a player.
  Kick:
    description: Kick a player.
  Mute:
    description: Mute a player.
  Unmute:
    description: Unmute a player.
  Tempmute:
    description: Temporarily mute a player.
  Ban:
    description: Ban a player.
  Unban:
    description: Unban a player.
  Tempban:
    description: Temporarily ban a player.
  Blacklist:
    description: Blacklist an IP address.
  Unblacklist:
    description: Unblacklists an IP address.
  History:
    description: View a players punishment history.
    aliases: [c, hist]
  ClearHistory:
    description: Clear a players punishment history.
    aliases: [ch, clearhist]
  Grant:
    description: Grant a player a rank.
  Grants:
    description: View a players grant history.
    aliases: [cg, granthistory, granthist]
  Ungrant:
    description: Revoke a players grant.
  ClearGrantHistory:
    description: Clear a players grant history.
    aliases: [cgh, cleargranthist]
  StaffChat:
    description: Talk privately with staff members.
    aliases: [sc]
  AdminChat:
    description: Talk privately with admins and above.
    aliases: [ac]
  ManagementChat:
    description: Talk privately with managers and above.
    aliases: [mc]
  ToggleStaffAlerts:
    description: Toggle on or off staff alerts.
    aliases: tsa
  Vanish:
    description: Vanish yourself or another player.