name: yoCore
version: ${project.version}
main: me.yochran.yocore.yoCore
api-version: 1.16
authors: [ Yochran ]
description: Remastered version of the vCores, combined into one plugin.
loadbefore:
  - yoBungee
permissions:
  yocore.resetstats:
    description: Permission
  yocore.unbounty:
    description: Permission
  yocore.economycommand:
    description: Permission
  yocore.ban:
    description: Permission
  yocore.blacklist:
    description: Permission
  yocore.clearhistory:
    description: Permission
  yocore.history:
    description: Permission
  yocore.kick:
    description: Permission
  yocore.mute:
    description: Permission
  yocore.warn:
    description: Permission
  yocore.unban:
    description: Permission
  yocore.unblacklist:
    description: Permission
  yocore.unmute:
    description: Permission
  yocore.alts:
    description: Permission
  yocore.broadcast:
    description: Permission
  yocore.buildmode:
    description: Permission
  yocore.clearchat:
    description: Permission
  yocore.clear:
    description: Permission
  yocore.echest:
    description: Permission
  yocore.staffalerts:
    description: Permission
  yocore.feed:
    description: Permission
  yocore.fly:
    description: Permission
  yocore.fly.others:
    description: Permission
  yocore.freeze:
    description: Permission
  yocore.gamemode:
    description: Permission
  yocore.heal:
    description: Permission
  yocore.invsee:
    description: Permission
  yocore.modmode:
    description: Permission
  yocore.mutechat:
    description: Permission
  yocore.seen:
    description: Permission
  yocore.seen.ip:
    description: Permission
  yocore.servermanager:
    description: Permission
  yocore.speed:
    description: Permission
  yocore.sudo:
    description: Permission
  yocore.teleport:
    description: Permission
  yocore.teleport.all:
    description: Permission
  yocore.vanish:
    description: Permission
  yocore.chats.staff:
    description: Permission
  yocore.chats.admin:
    description: Permission
  yocore.chats.management:
    description: Permission
  yocore.chatcolor:
    description: Permission
  yocore.cleargranthistory:
    description: Permission
  yocore.clearreports:
    description: Permission
  yocore.grant:
    description: Permission
  yocore.grant.owner:
    description: Permission
  yocore.grant.developer:
    description: Permission
  yocore.grant.manager:
    description: Permission
  yocore.grant.admin:
    description: Permission
  yocore.grant.seniormod:
    description: Permission
  yocore.grant.mod:
    description: Permission
  yocore.grant.trialmod:
    description: Permission
  yocore.grant.builder:
    description: Permission
  yocore.grant.default:
    description: Permission
  yocore.granthistory:
    description: Permission
  yocore.nick:
    description: Permission
  yocore.rank:
    description: Permission
  yocore.rankdisguise:
    description: Permission
  yocore.reporthistory:
    description: Permission
  yocore.tag:
    description: Permission
  yocore.mutechat.bypass:
    description: Permission
  yocore.user:
    description: Permission.
  yocore.silent:
    description: Permission.
  yocore.powertool:
    description: Permission.
  yocore.find:
    description: Permission.
  yocore.server:
    description: Permission.
  yocore.send:
    description: Permission.
  yocore.glist:
    description: Permission.
  yocore.skull:
    description: Permission.
  yocore.itemname:
    description: Permission.
commands:
  Setrank:
    description: Set a players rank.
    aliases: [sr, srank]
  Warn:
    description: Warn a player.
  Kick:
    description: Kick a player.
  Mute:
    description: Mute a player.
  Unmute:
    description: Unmute a player.
  Tempmute:
    description: Temporarily mute a player.
  Ban:
    description: Ban a player.
  Unban:
    description: Unban a player.
  Tempban:
    description: Temporarily ban a player.
  Blacklist:
    description: Blacklist an IP address.
  Unblacklist:
    description: Unblacklists an IP address.
  History:
    description: View a players punishment history.
    aliases: [c, hist]
  ClearHistory:
    description: Clear a players punishment history.
    aliases: [ch, clearhist]
  Grant:
    description: Grant a player a rank.
  Grants:
    description: View a players grant history.
    aliases: [cg, granthistory, granthist]
  Ungrant:
    description: Revoke a players grant.
  ClearGrantHistory:
    description: Clear a players grant history.
    aliases: [cgh, cleargranthist]
  StaffChat:
    description: Talk privately with staff members.
    aliases: [sc]
  AdminChat:
    description: Talk privately with admins and above.
    aliases: [ac]
  ManagementChat:
    description: Talk privately with managers and above.
    aliases: [mc]
  ToggleStaffAlerts:
    description: Toggle on or off staff alerts.
    aliases: tsa
  Vanish:
    description: Vanish yourself or another player.
    aliases: [v]
  Gamemode:
    description: Change your or another players gamemode.
    aliases: gm
  Gmc:
    description: Enter creative mode.
    aliases: gm1
  Gms:
    description: Enter Survival mode.
    aliases: gm0
  Gmsp:
    description: Enter spectator mode.
    aliases: gm2
  Gma:
    description: Enter adventure mode.
    aliases: gm3
  Heal:
    description: Heal yourself or another player.
  Feed:
    description: Feed yourself or another player.
  Clear:
    description: Clear your or another players inventory.
    aliases: ci
  ClearChat:
    description: Clear the chat.
  MuteChat:
    description: Mute the chat.
    aliases: mgc
  Fly:
    description: Change your or another players fly mode.
  Teleport:
    description: Teleport yourself to another player, or teleport a player to you, or teleport a player to another player.
    aliases: tp
  TeleportHere:
    description: Teleport another player to you.
    aliases: tphere
  TeleportAll:
    description: Teleport all players to yourself.
    aliases: tpall
  Freeze:
    description: Freeze a player.
    aliases: ss
  Modmode:
    description: Put you or another player into modmode.
    aliases: mod
  Report:
    description: Report a player for breaking the rules.
  BuildMode:
    description: Toggle your build mode.
    aliases: build
  Message:
    description: Privately message another player.
    aliases: [msg, whisper, w, tell, t]
  Reply:
    description: Reply to a player messaging you.
    aliases: r
  ToggleMessages:
    description: Toggle your private messages.
    aliases: tpm
  Alts:
    description: Get a players alternate accounts.
  OnlinePlayers:
    description: Get all online players.
    aliases: [list, whois]
  Invsee:
    description: See a players inventory.
  Rank:
    description: Add or remove ranks.
  ChatColor:
    description: Change your chat color.
    aliases: cc
  Broadcast:
    description: Broadcast a message to the server.
    aliases: [alert, bc]
  Settings:
    description: Change your player settings.
    aliases: options
  Speed:
    description: Change your or another players speed.
  Sudo:
    description: Make a player run a command or type something in chat.
  Balance:
    description: Get your or another players balance.
    aliases: [bal, money]
  Bounty:
    description: Bounty a player.
  Pay:
    description: Pay a player.
  Unbounty:
    description: Unbounty a player.
  Economy:
    description: Manage the economy.
    aliases: eco
  Stats:
    description: View a players stats.
  ResetStats:
    description: Reset a players stats.
  ToggleScoreboard:
    description: Toggle on or off the server scoreboard.
    aliases: tsb
  EnderChest:
    description: View a players ender chest.
    aliases: echest
  ReWarn:
    description: Rewarn a player.
  ReMute:
    description: Remute a player.
  ReTempMute:
    description: Temporarily remute a player.
  ReBan:
    description: Reban a player.
  ReTempBan:
    description: Temporarily reban a player.
  ReBlacklist:
    description: Reblacklist a player.
  ServerManager:
    description: Manage the server.
    aliases: sm
  Ping:
    description: Get a players ping.
  Reports:
    description: View a players report history.
    aliases: cr
  ClearReports:
    description: Clear a players report history.
    aliases: crh
  Seen:
    description: Get info on a player.
    aliases: [pinfo, pi, playerinfo]
  RankDisguise:
    description: Disguise a players rank.
  Nickname:
    description: Set your or another players nickname.
    aliases: nick
  RealName:
    description: Get the real name behind a nickname.
  Tags:
    description: Set your tag.
  Tag:
    description: Manage tags.
  User:
    description: Add remove or list permissions under a user.
    aliases: player
  Powertool:
    description: Set a powertool.
    aliases: pt
  Find:
    description: Find a player connected to the server.
  Server:
    description: Send yourself to a server.
  Send:
    description: Send yourself or another player to a server.
  GList:
    description: List all servers and their players.
  Hub:
    description: Travel to the hub server.
    aliases: [lobby, l]
  Spawn:
    description: Travel to spawn.
  Skull:
    description: Get a players skull.
  ItemName:
    description: Rename an item.
    aliases: iname