name: yoCore
version: ${project.version}
main: me.yochran.yocore.yoCore
api-version: 1.16
authors: [ Yochran ]
description: Remastered version of the vCores, combined into one plugin.
commands:
  Setrank:
    description: Set a players rank.
    aliases: [sr, srank]
  Warn:
    description: Warn a player.
  Kick:
    description: Kick a player.
  Mute:
    description: Mute a player.
  Unmute:
    description: Unmute a player.
  Tempmute:
    description: Temporarily mute a player.
  Ban:
    description: Ban a player.
  Unban:
    description: Unban a player.
  Tempban:
    description: Temporarily ban a player.
  Blacklist:
    description: Blacklist an IP address.
  Unblacklist:
    description: Unblacklists an IP address.
  History:
    description: View a players punishment history.
    aliases: [c, hist]
  ClearHistory:
    description: Clear a players punishment history.
    aliases: [ch, clearhist]
  Grant:
    description: Grant a player a rank.
  Grants:
    description: View a players grant history.
    aliases: [cg, granthistory, granthist]
  Ungrant:
    description: Revoke a players grant.
  ClearGrantHistory:
    description: Clear a players grant history.
    aliases: [cgh, cleargranthist]
  StaffChat:
    description: Talk privately with staff members.
    aliases: [sc]
  AdminChat:
    description: Talk privately with admins and above.
    aliases: [ac]
  ManagementChat:
    description: Talk privately with managers and above.
    aliases: [mc]
  ToggleStaffAlerts:
    description: Toggle on or off staff alerts.
    aliases: tsa
  Vanish:
    description: Vanish yourself or another player.
    aliases: [v]
  Gamemode:
    description: Change your or another players gamemode.
    aliases: gm
  Gmc:
    description: Enter creative mode.
    aliases: gm1
  Gms:
    description: Enter Survival mode.
    aliases: gm0
  Gmsp:
    description: Enter spectator mode.
    aliases: gm2
  Gma:
    description: Enter adventure mode.
    aliases: gm3
  Heal:
    description: Heal yourself or another player.
  Feed:
    description: Feed yourself or another player.
  Clear:
    description: Clear your or another players inventory.
    aliases: ci
  ClearChat:
    description: Clear the chat.
  MuteChat:
    description: Mute the chat.
    aliases: mgc
  Fly:
    description: Change your or another players fly mode.
  Teleport:
    description: Teleport yourself to another player, or teleport a player to you, or teleport a player to another player.
    aliases: tp
  TeleportHere:
    description: Teleport another player to you.
    aliases: tphere
  TeleportAll:
    description: Teleport all players to yourself.
    aliases: tpall
  Freeze:
    description: Freeze a player.
    aliases: ss
  Modmode:
    description: Put you or another player into modmode.
    aliases: mod
  Report:
    description: Report a player for breaking the rules.
  BuildMode:
    description: Toggle your build mode.
    aliases: build
  Message:
    description: Privately message another player.
    aliases: [msg, whisper, w, tell, t]
  Reply:
    description: Reply to a player messaging you.
    aliases: r
  ToggleMessages:
    description: Toggle your private messages.
    aliases: tpm
  Alts:
    description: Get a players alternate accounts.
  OnlinePlayers:
    description: Get all online players.
    aliases: [list, whois]
  Invsee:
    description: See a players inventory.
  Rank:
    description: Add or remove ranks.
  ChatColor:
    description: Change your chat color.
    aliases: cc
  Broadcast:
    description: Broadcast a message to the server.
    aliases: [alert, bc]
  Settings:
    description: Change your player settings.
    aliases: options
  Speed:
    description: Change your or another players speed.
  Sudo:
    description: Make a player run a command or type something in chat.
  Balance:
    description: Get your or another players balance.
    aliases: [bal, money]
  Bounty:
    description: Bounty a player.
  Pay:
    description: Pay a player.
  Unbounty:
    description: Unbounty a player.
  Economy:
    description: Manage the economy.
    aliases: eco
  Stats:
    description: View a players stats.
  ResetStats:
    description: Reset a players stats.
  ToggleScoreboard:
    description: Toggle on or off the server scoreboard.
    aliases: tsb